### ISSUE TITLE
Cannot Get py to Run

### ISSUE THREAD

**Issue by justjoe96** [bbartling/ot-lan-rest-server#1]
Hi,

When I try to run python3 app/rpc-server.py --host 0.0.0.0 --port 8080  --debug I get :

 File "/home/ats/BacNet_RCP/app/rpc-server.py", line 49, in <module>
    from models import BaseResponse, WritePropertyRequest
  File "/home/ats/BacNet_RCP/app/models.py", line 1, in <module>
    from pydantic import BaseModel, conint, Field, ValidationError, field_validator

How do I properly install this code?

**Comment by bbartling** [comment]
Hi. Did the

$ python -m pip install bacpypes3 ifaddr fastapi uvicorn

Work okay? On linux too right?

Make sure you run the $ app/rpc server .py file in the root directory of
the project.

Maybe state what version of py and OS you are using top. Paste in a
screenshot too if it's not working.

**Comment by bbartling** [comment]
So i am on a freshly imaged rasp pi on my test bench. Hopefully these screenshots help. It appears to be working for me but what I had to do is setup a virtual environment where in the screenshot below is the red arrow where then `pip install` the packages.

![image](https://github.com/bbartling/bacpypes3RcpServer/assets/29737117/35beed35-8249-45a5-8b5e-9e39cb524cf1)

And then running the app like this:
![image](https://github.com/bbartling/bacpypes3RcpServer/assets/29737117/3f6028b7-acf0-4160-ae1b-3972b92ff346)


I can then dial into it on the rasp pi's IP address where on my LAN its .102:
http://192.168.0.102:5000/docs

Let me know if I can help you at all. I dont think the bacpypes3 stack runs on Windows. I also have some fake BACnet apps you can run too if you have some extra linux devices lying around...

**Comment by justjoe96** [comment]
Yeah, I ended up going another direction. Thanks.

Joe

**Comment by bbartling** [comment]
sounds good feel free to ask questions else there is a discord channel that
is real neat too that I am part of as well.
https://discord.gg/nCq4jJCx

Lots of good people on there for BACnet questions... if you join there is
an "intro" section where people just state there background and work
experience, etc...
